### ISSUE TITLE
Use aggfunc='last' in restructure_data

### ISSUE THREAD

**Issue by UlrichThiess** [CSS-Electronics/dashboard-writer#12]
If we measure things that could be on or off the aggfunc='mean' seems not to be correct.

Example the break: (It could be 0, 1, or 3)
![grafik](https://user-images.githubusercontent.com/79257887/219852578-2c4ec553-0032-486d-b72d-25eca34b59a5.png)

If we measure speed 'mean' is mathematical correct, but 'last' should also work because the sample steps are near enough.

Source: utils.py

**Comment by MatinF** [comment]
Hi Ulrich,

Fully valid point. The concern with using "last" instead of "mean" would be that for continuous signals the result can become quite incorrect if you're e.g. resampling to a 10 second interval. An option might be to use `np.median`, though there might be other downsides to that: https://numpy.org/doc/stable/reference/generated/numpy.median.html

For now, the choice has been made based on our assumption that the most common use case will be for continuous type signals. If a signal changes in discrete steps, the assumption is that the result will still be reasonably valid if the signal stays within a specific step for a period that exceeds the resampling period significantly, as the user can then still gain a result that will be as expected within Grafana (e.g. by using Grafana's "last" instead of "mean" in panels), except for the 'edges' where the signal changes value. For a frequently changing signal that moves in discrete steps, however, script-based resampling will not be ideal either way in my opinion. Here it may be better to "split" your signals into two chunks and process them individually.

For example, you could create an inputs_continuous.py and inputs_discrete.py. The first would filter only signals that are continuous and where you want to resample them. The second would filter only signals that are discrete. For the second you then disable resampling by settings `res=""`. In your main.py you can then load both of the inputs files, create a list of them and loop through the entire process for each of them separately. It'll be a bit slower, but may be the best solution for now.

Alternatively, you can ensure your raw data is pre-filtered to the ideal frequency on the CANedge. When you then process the data, simply set the inputs.py `res=""` to skip the `restructure_data` step entirely. 

Hope clear, else reopen :-)
